import { BaseContextProvider } from "../../core/context";
import {
    ContextItem,
    ContextProviderDescription,
    ContextProviderExtras,
} from "../../core/index";

/**
 * Simple custom context provider that provides basic system information
 */
class SimpleInfoProvider extends BaseContextProvider {
  static description: ContextProviderDescription = {
    title: "simple-info",
    displayTitle: "Simple Info",
    description: "Get basic system and environment information",
    type: "normal",
    renderInlineAs: "System information",
  };

  getContextItems(
    query: string,
    extras: ContextProviderExtras,
  ): Promise<ContextItem[]> {
    // Get basic system information
    const nodeVersion = process.version;
    const platform = process.platform;
    const architecture = process.arch;
    const memoryUsage = process.memoryUsage();
    const cwd = process.cwd();
    
    // Format memory usage
    const formatBytes = (bytes: number) => {
      const mb = bytes / (1024 * 1024);
      return `${mb.toFixed(2)} MB`;
    };
    
    // Format the content
    const content = `System Information:

🖥️ Platform: ${platform}
📦 Node.js Version: ${nodeVersion}
🔧 Architecture: ${architecture}
📁 Working Directory: ${cwd}

Memory Usage:
- RSS (Resident Set Size): ${formatBytes(memoryUsage.rss)}
- Heap Total: ${formatBytes(memoryUsage.heapTotal)}
- Heap Used: ${formatBytes(memoryUsage.heapUsed)}
- External: ${formatBytes(memoryUsage.external)}

Environment:
- NODE_ENV: ${process.env.NODE_ENV || 'not set'}
- Process ID: ${process.pid}
- Parent Process ID: ${process.ppid}

This information was generated by the Custom Simple Info Provider.`;

    return Promise.resolve([
      {
        description: "Basic system and environment information",
        content,
        name: "System Info",
      },
    ]);
  }
}

export default SimpleInfoProvider; 